"""final_init

Revision ID: dd3c8e736e31
Revises: 
Create Date: 2025-12-27 00:57:25.213948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3c8e736e31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automod_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('exempt_roles', sa.JSON(), nullable=False),
    sa.Column('exempt_channels', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automod_rules_guild_id'), 'automod_rules', ['guild_id'], unique=False)
    op.create_table('custom_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('cooldown', sa.Integer(), nullable=False),
    sa.Column('permission_role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_commands_guild_id'), 'custom_commands', ['guild_id'], unique=False)
    op.create_table('guilds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guilds_discord_id'), 'guilds', ['discord_id'], unique=True)
    op.create_table('level_rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('level_requirement', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_rewards_guild_id'), 'level_rewards', ['guild_id'], unique=False)
    op.create_table('leveling_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('xp_rate', sa.Integer(), nullable=False),
    sa.Column('no_xp_channels', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leveling_configs_guild_id'), 'leveling_configs', ['guild_id'], unique=True)
    op.create_table('log_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_events_guild_id'), 'log_events', ['guild_id'], unique=False)
    op.create_table('moderation_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('moderator_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_cases_guild_id'), 'moderation_cases', ['guild_id'], unique=False)
    op.create_index(op.f('ix_moderation_cases_user_id'), 'moderation_cases', ['user_id'], unique=False)
    op.create_table('reaction_role_menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaction_role_menus_guild_id'), 'reaction_role_menus', ['guild_id'], unique=False)
    op.create_table('scheduled_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cron', sa.String(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_messages_guild_id'), 'scheduled_messages', ['guild_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_guild_id'), 'tickets', ['guild_id'], unique=False)
    op.create_index(op.f('ix_tickets_owner_id'), 'tickets', ['owner_id'], unique=False)
    op.create_table('user_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_levels_guild_id'), 'user_levels', ['guild_id'], unique=False)
    op.create_index(op.f('ix_user_levels_user_id'), 'user_levels', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_table('warnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('moderator_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warnings_guild_id'), 'warnings', ['guild_id'], unique=False)
    op.create_index(op.f('ix_warnings_user_id'), 'warnings', ['user_id'], unique=False)
    op.create_table('oauth_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_messages')
    op.drop_table('oauth_sessions')
    op.drop_index(op.f('ix_warnings_user_id'), table_name='warnings')
    op.drop_index(op.f('ix_warnings_guild_id'), table_name='warnings')
    op.drop_table('warnings')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_levels_user_id'), table_name='user_levels')
    op.drop_index(op.f('ix_user_levels_guild_id'), table_name='user_levels')
    op.drop_table('user_levels')
    op.drop_index(op.f('ix_tickets_owner_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_guild_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_scheduled_messages_guild_id'), table_name='scheduled_messages')
    op.drop_table('scheduled_messages')
    op.drop_index(op.f('ix_reaction_role_menus_guild_id'), table_name='reaction_role_menus')
    op.drop_table('reaction_role_menus')
    op.drop_index(op.f('ix_moderation_cases_user_id'), table_name='moderation_cases')
    op.drop_index(op.f('ix_moderation_cases_guild_id'), table_name='moderation_cases')
    op.drop_table('moderation_cases')
    op.drop_index(op.f('ix_log_events_guild_id'), table_name='log_events')
    op.drop_table('log_events')
    op.drop_index(op.f('ix_leveling_configs_guild_id'), table_name='leveling_configs')
    op.drop_table('leveling_configs')
    op.drop_index(op.f('ix_level_rewards_guild_id'), table_name='level_rewards')
    op.drop_table('level_rewards')
    op.drop_index(op.f('ix_guilds_discord_id'), table_name='guilds')
    op.drop_table('guilds')
    op.drop_index(op.f('ix_custom_commands_guild_id'), table_name='custom_commands')
    op.drop_table('custom_commands')
    op.drop_index(op.f('ix_automod_rules_guild_id'), table_name='automod_rules')
    op.drop_table('automod_rules')
    # ### end Alembic commands ###
