"""add economy system

Revision ID: 2f87a2b9c1d4
Revises: 1e5601fe9ab3
Create Date: 2025-12-28 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f87a2b9c1d4'
down_revision = '1e5601fe9ab3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economy_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('last_daily', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economy_profiles_guild_id'), 'economy_profiles', ['guild_id'], unique=False)
    op.create_index(op.f('ix_economy_profiles_user_id'), 'economy_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_economy_profiles_user_id'), table_name='economy_profiles')
    op.drop_index(op.f('ix_economy_profiles_guild_id'), table_name='economy_profiles')
    op.drop_table('economy_profiles')
    # ### end Alembic commands ###
